/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module extra_7 (
    input [7:0] sum,
    input [7:0] a,
    input [7:0] b,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    v = (a[7+0-:1] & ~b[7+0-:1] & (~sum[7+0-:1])) | ((~a[7+0-:1]) & (b[7+0-:1]) & sum[7+0-:1]);
    n = sum[7+0-:1];
    z = (~|sum);
  end
endmodule
